# This inventory describe a HA typology with stacked etcd (== same nodes as control plane)
# and 3 worker nodes
# See https://docs.ansible.com/ansible/latest/inventory_guide/intro_inventory.html
# for tips on building your # inventory

# Configure 'ip' variable to bind kubernetes services on a different ip than the default iface
# We should set etcd_member_name for etcd cluster. The node that are not etcd members do not need to set the value,
# or can set the empty string value.
[kube_control_plane]
controller-0 ansible_host=35.247.39.12  #ip=10.240.0.10 etcd_member_name=etcd1
controller-1 ansible_host=34.168.43.67  #ip=10.240.0.11 etcd_member_name=etcd2
controller-2 ansible_host=34.19.7.252  #ip=10.240.0.12 etcd_member_name=etcd3

[etcd:children]
kube_control_plane

[kube_node]
worker-0 ansible_host=34.169.249.135 #ip=10.240.0.20
